#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc none /proc
echo "Good morning!"
sleep 5 # give kernel a moment to set everything up
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
#exec /sbin/init $*
echo "Hi there!"
export ROOT="/dev/mmcblk1p9"
mkdir /mnt/root
echo "Mount..."
/bin/mount $ROOT /mnt/root
/bin/mount -t sysfs none /mnt/root/sys
/bin/mount -t proc none /mnt/root/proc
/bin/mount -t devtmpfs none /mnt/root/dev
/bin/mount -t tmpfs none /mnt/root/tmp
echo mounted $ROOT on /mnt/root
/bin/mount
echo "Launching switch_root..."
exec /sbin/switch_root /mnt/root /sbin/init

